# Generated by Django 5.1.1 on 2025-08-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reviews',
            name='unique_review_per_author',
        ),
    ]
