# Generated by Django 5.1.1 on 2025-08-22 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviews_unique_review_per_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
