# Generated by Django 5.1.1 on 2025-08-22 10:04

import review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_reviews_unique_review_per_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Выберите Slug', unique=True, validators=[review.models.validate_slug], verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(max_length=20, unique=True, validators=[review.models.validate_slug], verbose_name='Слаг'),
        ),
    ]
