# Generated by Django 5.1.1 on 2025-08-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='title',
            new_name='name',
        ),
    ]
