# Generated by Django 5.1.1 on 2025-08-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_rename_title_genre_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='title',
            new_name='name',
        ),
    ]
