# Generated by Django 5.1.1 on 2025-08-25 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='Год должен быть не меньше 1000'), django.core.validators.MaxValueValidator(2100, message='Год должен быть не больше 2100')], verbose_name='Год произведения'),
        ),
    ]
